# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{mapfish}
  s.version = "1.3.6"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Pirmin Kalberer"]
  s.date = %q{2011-07-07}
  s.description = %q{MapFish is a flexible and complete framework for building rich web-mapping applications. Homepage: mapfish.org}
  s.email = %q{pka@sourcepole.ch}
  s.files = [
    ".gitignore",
    "COPYING.LESSER",
    "README",
    "Rakefile",
    "VERSION",
    "init.rb",
    "install.rb",
    "lib/generators/mapfish/print_controller/USAGE",
    "lib/generators/mapfish/print_controller/print_controller_generator.rb",
    "lib/generators/mapfish/print_controller/templates/config.yaml",
    "lib/generators/mapfish/print_controller/templates/controller.rb",
    "lib/generators/mapfish/resource/USAGE",
    "lib/generators/mapfish/resource/resource_generator.rb",
    "lib/generators/mapfish/resource/templates/controller.rb",
    "lib/geojson.rb",
    "lib/mapfish.rb",
    "lib/mapfish_core_extensions/active_record/base.rb",
    "lib/mapfish_core_extensions/array.rb",
    "lib/print.rb",
    "lib/tasks/mapfish_tasks.rake",
    "mapfish.gemspec",
    "print/print-standalone.jar",
    "test/geojson_test.rb",
    "uninstall.rb"
  ]
  s.homepage = %q{http://mapfish.org/doc/implementations/rails.html}
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{Mapfish server plugin for Ruby on Rails}

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<spatial_adapter>, [">= 0"])
      s.add_runtime_dependency(%q<GeoRuby>, [">= 0"])
      s.add_runtime_dependency(%q<POpen4>, [">= 0.1.4"])
    else
      s.add_dependency(%q<spatial_adapter>, [">= 0"])
      s.add_dependency(%q<GeoRuby>, [">= 0"])
      s.add_dependency(%q<POpen4>, [">= 0.1.4"])
    end
  else
    s.add_dependency(%q<spatial_adapter>, [">= 0"])
    s.add_dependency(%q<GeoRuby>, [">= 0"])
    s.add_dependency(%q<POpen4>, [">= 0.1.4"])
  end
end

